FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

# 1. Copy the solution and project files to perform a restore.
COPY KKday.B2D.Web.InternAgent.sln ./
COPY KKday.B2D.Web.InternAgent/KKday.B2D.Web.InternAgent.csproj KKday.B2D.Web.InternAgent/
RUN dotnet restore KKday.B2D.Web.InternAgent.sln

# 2. Copy the remaining source code (ensure the Resources folder and all .resx files are included).
COPY KKday.B2D.Web.InternAgent/ KKday.B2D.Web.InternAgent/

# 3. Perform the publish operation (remove `--no-restore` to prevent compilation errors caused by incomplete restoration of satellite DLLs for multiple locales).
RUN dotnet publish KKday.B2D.Web.InternAgent/KKday.B2D.Web.InternAgent.csproj -c Release -o /app/publish

# 4. Runtime environment phase
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app

# Copy in all files generated by the build process (including subfolders for various locales, such as /zh-TW/).
COPY --from=build /app/publish .

# Match your port settings.
ENV ASPNETCORE_URLS=http://0.0.0
EXPOSE 8080

ENTRYPOINT ["dotnet", "KKday.B2D.Web.InternAgent.dll"]
